### ISSUE TITLE
/opt/bitnami/logstash/data is not writable.

### ISSUE THREAD

**Issue by eloo** [bitnami/bitnami-docker-logstash#10]
**Description**

Hi, i try to run this docker image using the related helm chart without any persistence and it seems that there is a ownership issue in the container.

**Steps to reproduce the issue:**

1. Deploy helm chart with persistence disabled
2. See that container is crashing

**Describe the results you received:**

In the logs of the container i see the following error:
```
Your settings are invalid. Reason: Path "/opt/bitnami/logstash/data" must be a writable directory. It is not writable.
```

If i check the permission in the container i see the following:

```
ls -al /opt/bitnami/logstash
drwxr-xr-x 1 root     root     36 Jan 13 21:11 .
drwxrwxr-x 1 root     root     22 Jan 13 21:09 ..
-rw-r--r-- 1 root     root      0 Jan 13 18:19 .buildcomplete
-rw-r--r-- 1 root     root   2276 Jan 13 18:19 CONTRIBUTORS
-rw-r--r-- 1 root     root   4050 Jan 13 18:19 Gemfile
-rw-r--r-- 1 root     root  27702 Jan 13 18:19 Gemfile.lock
-rw-r--r-- 1 root     root  11358 Jan 13 18:19 LICENSE.txt
-rw-r--r-- 1 root     root 424030 Jan 13 18:19 NOTICE.TXT
drwxr-xr-x 2 root     root   4096 Jan 13 18:29 bin
drwxrwxr-x 1 logstash root    172 Jan 13 21:11 config
drwxr-xr-x 2 root     root      6 Jan  1  1970 data
drwxr-xr-x 6 root     root     84 Jan 13 18:29 lib
drwxr-xr-x 2 root     root     33 Jan 13 18:29 licenses
drwxr-xr-x 4 root     root     90 Jan 13 18:29 logstash-core
drwxr-xr-x 3 root     root     86 Jan 13 18:29 logstash-core-plugin-api
drwxr-xr-x 4 root     root     55 Jan 13 18:29 modules
drwxrwxr-x 2 logstash root      6 Jan 13 21:11 pipeline
drwxr-xr-x 3 root     root     30 Jan 13 18:29 tools
drwxr-xr-x 4 root     root     33 Jan 13 18:29 vendor
```

I guess here the data directory should have also the logstash user as owner.

**Describe the results you expected:**

That the container starts because the default data directory has the correct ownership.

Thanks

**Comment by marcosbc** [comment]
Hi @eloo, note that the folder where persisted folders are stored is `/bitnami/logstash`. If you enter the shell of the container (you can do that in the chart by enabling diagnostics mode), you should see this when executing the command `ls -la /bitnami/logstash/`:

```
I have no name!@a743aa8dba90:/opt/bitnami/logstash$ ls -la /bitnami/logstash/
total 28
drwxrwxr-x 1 logstash root 4096 Jan 26 20:01 .
drwxr-xr-x 1 root     root 4096 Jan 26 20:01 ..
drwxrwxr-x 2 logstash root 4096 Jan 26 20:01 config
drwxrwxr-x 1 logstash root 4096 Jan 27 09:45 data
drwxrwxr-x 2 logstash root 4096 Jan 26 20:01 pipeline
```

In addition, note that the container itself works just fine without persistence, for instance this `docker-compose.yml` deploys perfectly:

```
cat docker-compose.yml
version: '2'
services:
  logstash:
    image: docker.io/bitnami/logstash:7
    ports:
      - 8080:8080
    #volumes:
    #  - logstash_data:/bitnami
#volumes:
#  logstash_data:
#    driver: local
```

So this issue is more likely related to the chart itself. Have you been able to confirm that indeed you have disabled persistence for the chart?

**Comment by eloo** [comment]
@marcosbc 
Running the following command will give you the same output as i can see in my helm chart setup

```
docker run -it --rm bitnami/logstash:7.16.3-debian-10-r11 ls -al
```

so maybe its a bug in the debian version of the docker image.. not sure what the image you are using your compose is using as base

So for me it looks still like an issue in the image.
And yes i have checked that persistence is disable in my chart ;)

**Comment by marcosbc** [comment]
@eloo It could be that you are mounting a custom configuration file. If you run these commands, you will see that the Logstash data directory is configured to be `/bitnami/logstash/data`:

```console
$ docker run -it --rm bitnami/logstash:7.16.3-debian-10-r11 cat /opt/bitnami/logstash/config/logstash.yml | grep '^path\.data'
path.data: /bitnami/logstash/data
$ docker run -it --rm bitnami/logstash:7.16.3-debian-10-r11 ls -al /bitnami/logstash
logstash 10:20:15.92
logstash 10:20:15.92 Welcome to the Bitnami logstash container
logstash 10:20:15.92 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-logstash
logstash 10:20:15.92 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-logstash/issues
logstash 10:20:15.93

total 20
drwxrwxr-x 5 logstash root 4096 Jan 25 19:30 .
drwxr-xr-x 3 root     root 4096 Jan 25 19:30 ..
drwxrwxr-x 2 logstash root 4096 Jan 25 19:30 config
drwxrwxr-x 2 logstash root 4096 Jan 25 19:30 data
drwxrwxr-x 2 logstash root 4096 Jan 25 19:30 pipeline
```

which is writable by the `logstash` user.

**Comment by eloo** [comment]
Ah okay. thats interesting. 

The directory you are referring seems to be okay.  (/bitnami/logstash)

But the actual working directory (/opt/bitnami/logstash) seems to lacks the logstash ownership. 
And the environments of the logstash container are pointing to the /opt/bitnami/logstash directory.

```
LOGSTASH_BASE_DIR=/opt/bitnami/logstash
LOGSTASH_CONF_DIR=/opt/bitnami/logstash/config
LOGSTASH_PIPELINE_CONF_FILE=/opt/bitnami/logstash/pipeline/logstash.conf
```

but there are also some envs like this
```
LOGSTASH_VOLUME_DIR=/bitnami/logstash
LOGSTASH_MOUNTED_PIPELINE_CONF_DIR=/bitnami/logstash/pipeline
```

further the `/opt/bitnami/logstash` has the same directories as the `/bitnami/logstash` directory. 
So this seems to be duplicated somehow. 

And i have also found the issue. 
It seems the `path.data: /bitnami/logstash/data` is only set in the example/default config.
If you use a custom config for the logstash.yml and do not set the `path.data` then the `/opt/bitnami/logstash/data` directory will be used which is lacking permissions

**Comment by marcosbc** [comment]
Great to see you found the issue @eloo! The `path.data` configuration is indeed required when setting a custom config file.

**Comment by eloo** [comment]
IMHO this is still open.

we still have a fallback directory which is not writable
