### ISSUE TITLE
Installing plugins

### ISSUE THREAD

**Issue by vodwood** [bitnami/bitnami-docker-logstash#2]
Not an issue per se, but what would a real production workflow involving logstash plugins would look like with this container?
This is a non-root container and installing plugins via /bin/logstash-plugin is impossible.

How would one actually use this if the use case goes beyond default logstash plugins?

**Comment by FraPazGal** [comment]
Hello @vodwood,

Currently, this container doesn't have the option of installing plugins via an env. A simple solution to this would be to customise our logstash image to install your need plugins at build. You can find more information about customising our containers [here](https://github.com/bitnami/bitnami-docker-mariadb#extend-this-image), though an exmple to this would be:

```Dockerfile
FROM bitnami/logstash

## Change user to perform privileged actions
USER 0
RUN bin/logstash-plugin install logstash-pluginname
## Revert to the original non-root user
USER 1001
```

You could use `docker exec -u root` into the container and execute the commands at run time, though I would say the first option is preferable.
