### ISSUE TITLE
LOGSTASH_HEAP_SIZE should not default to 1g

### ISSUE THREAD

**Issue by ikus060** [bitnami/bitnami-docker-logstash#3]
Cannot use automatic calculation of the memory because LOGSTASH_HEAP_SIZE is default to 1g.

Looing at liblogstash.sh, I see some code that can be used to calculate the appropriate memory heap to be allocation to the logstash process, but this peace of code cannot be trigger because LOGSTASH_HEAP_SIZE is default to 1g when empty.

https://github.com/bitnami/bitnami-docker-logstash/blob/b409b259b67c2fbadf1da13c7bdc0c1bb7aab69f/7/debian-10/rootfs/opt/bitnami/scripts/liblogstash.sh#L52

**Comment by ikus060** [comment]
Even worst, the calculation of the memory is based on host memoru `/proc/meminfo` instead of `/sys/fs/cgroup/memory/memory.stat`

**Comment by rafariossaa** [comment]
Hi,
  Thanks you very much for spotting this.

  About the proper memory calculation, could you point me to some reference on how to calculate the free memory using `memory.stat` ? or even better, would you like to send a PR ? We will be glad to review and merge it .
