### ISSUE TITLE
How could you unsubscribe to this image from Azure Portal? Subscribed the image but no longer required. Due to which the image is pushed/imported daily to ACR post deletion.

### ISSUE THREAD

**Issue by punedhir** [bitnami/bitnami-docker-logstash#7]
**Description**

**Steps to reproduce the issue:**

1. Go to Azure Portal - Type Logstash Exporter packaged by Bitnami in Search Pane
2. You could subscribe this package but there is no option to unsusbscribe it.
3. Additionally, it keeps on pushing/importing the image to ACR which is no longer required.

**Describe the results you received:**

Image getting pushed/ imported daily to ACR which is no longer required.

**Describe the results you expected:**

Unsubscribe button or cancelling the image push to the ACR.

**Additional information you deem important (e.g. issue happens only occasionally):**

NA

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Azure

**Comment by alvneiayu** [comment]
hi @punedhir 

Sorry but this is a problem related to the Azure Portal. I suggest you to write to Azure Support. We don't have any control in the Azure Portal. 

Thanks a lot

Álvaro
